import Head from "next/head";

import SidebarMenu from "@/components/SidebarMenu";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import Progress from "@/components/Progress";
import ScrollToTopButton from "@/components/ScrollToTopButton";

export default function Home() {
  return (
    <>
      <Head>
        <title>Yuan Shuo Hsu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SidebarMenu />
      <Header />
      <Banner />
      <Progress />
      <ScrollToTopButton />
    </>
  );
}
